### ISSUE TITLE
image from POST does not show

### ISSUE THREAD

**Issue by mavs1971** [Dominus77/yii2-blog#2]
hi, thanks for this template, i seems to be an excelent tools.

but when you create post and you try to view in frontend app, the images does not show at all. only when you are log in you can view imagen on the frontend. 

the images in the protend must be view for all visitors, not only de sing in

**Comment by Dominus77** [comment]
Hi! What images are not displayed on you? I was unable to reproduce your situation.
![Снимок экрана от 2021-04-06 02-12-43](https://user-images.githubusercontent.com/9594483/113637817-2f631380-967e-11eb-9959-abcf080da5fb.png)

**Comment by Dominus77** [comment]
[The project is under construction.](https://github.com/Dominus77/yii2-blog#yii2-blog-application)
